// import React, { useState } from 'react';
// import './Planyourdiet.css';

// function PlanYourDiet() {
//   const [autoGeneratedMeals, setAutoGeneratedMeals] = useState([]);

//   const generateDietChart = () => {
//     const meals = [
//       {
//         name: "Breakfast",
//         foods: [
//           "Oatmeal with berries", 
//           "Greek yogurt with honey", 
//           "Smoothie with spinach and banana",
//           "Idli with sambar", 
//           "Masala chai"
//         ],
//       },
//       {
//         name: "Lunch",
//         foods: [
//           "Grilled chicken salad", 
//           "Quinoa with vegetables", 
//           "Turkey sandwich with whole grain bread",
//           "Dal with chapati", 
//           "Raita", 
//           "Buttermilk"
//         ],
//       },
//       {
//         name: "Dinner",
//         foods: [
//           "Baked salmon with asparagus", 
//           "Stir-fried tofu with broccoli", 
//           "Lean beef with sweet potatoes",
//           "Paneer tikka", 
//           "Palak paneer with brown rice", 
//           "Lassi"
//         ],
//       },
//     ];

//     setAutoGeneratedMeals(meals);
//   };

//   return (
//     <div className="plan-your-diet">
//       <h2>Get a Diet Plan</h2>
//       <button onClick={generateDietChart}>Generate Diet Plan</button>
//       {autoGeneratedMeals.length > 0 && (
//         <div className="diet-chart">
//           <h3>Your Suggested Meals</h3>
//           <table>
//             <thead>
//               <tr>
//                 <th>Meal</th>
//                 <th>Suggested Foods</th>
//               </tr>
//             </thead>
//             <tbody>
//               {autoGeneratedMeals.map((item, index) => (
//                 <tr key={index}>
//                   <td>{item.name}</td>
//                   <td>
//                     <ul>
//                       {item.foods.map((food, idx) => (
//                         <li key={idx}>{food}</li>
//                       ))}
//                     </ul>
//                   </td>
//                 </tr>
//               ))}
//             </tbody>
//           </table>
//         </div>
//       )}
//     </div>
//   );
// }

// export default PlanYourDiet;
